#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    [default.curl_tests]
        # Default JSON answer should contain mollysocket string
        home.expect_content = "mollysocket"
        home.auto_test_assets = false
